---
kind: pipeline
type: docker
name: drollcaller

steps:

  - name: build
    image: plugins/docker
    settings:
      username: drone
      password:
        from_secret: drone_registry_passwd
      registry: registry.mandragot.org
      repo: registry.mandragot.org/drollcaller
      tags: latest