---
kind: pipeline
type: docker
name: rocknroller

steps:

  - name: build
    image: plugins/docker
    settings:
      username: ezwen
      password:
        from_secret: ezwen_passwd
      registry: registry.mandragot.org
      repo: registry.mandragot.org/rocknroller
      tags: latest