---
kind: pipeline
type: docker
name: rocknroller

steps:

  - name: build
    image: plugins/docker
    settings:
      username: drone
      password:
        from_secret: registry_passwd
      registry: registry.mandragot.org
      repo: registry.mandragot.org/rocknroller
      tags: latest

image_pull_secrets:
  - registry_auth