description: "Mandragot"
timeout: "10s"
periodicity: "60m"
timezone: "Europe/Paris"
sleep:
  from: "03:30"
  to: "04:45"


checks:

  - type: synapse
    description: "Synapse 443"
    domain: "mandragot.org"
    port: "443"

  - type: synapse
    description: "Synapse 8448"
    domain: "mandragot.org"
    port: "8448"

  - type: webTitle
    description: "Codimd"
    url: "http://md.mandragot.org/"
    title: "Collaborative markdown notes"

  - type: webTitle
    description: "Frontpage"
    url: "http://mandragot.org/"
    title: "Mandragot"

  - type: webTitle
    description: "TTRSS"
    url: "https://feeds.mandragot.org"
    title: "Tiny Tiny RSS : Login"

  - type: webContent
    description: "Admin docs"
    url: "http://docs.admin.mandragot.org/"
    content: "401 Unauthorized"

  - type: webContent
    description: "Traefik admin interface"
    url: "http://traefik.admin.mandragot.org/"
    content: "401 Unauthorized"

  - type: ssh
    description: "SSH 22"
    host: "mandragot.org"
    port: 22
    key: "mandragot.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC33f3hW1VvhKXEyU+sOvJ2JQSpu2uBO6/Hc12HXVuk11C0s06z48BWqYvCNrkiVzf//2Z0ceGWqTe1j9ddR1mBpttidI9LebCJmTye73v4qSMW5y+O381YUTan5ZjBbnUYFlcJgeOKgGaKUmrFei9n+OLu/8IoJ1QT7bwbyvUE+oKrWVuh0QBcc2k3DeZ2gsaxN+6YOmpZkmb8BNN5YHZ4JWCwf3LvVr3QCRqfPUEAV4h1D8w7Ig94T1ZMj2IR4EtmSFY6T9GmKhP2z1e535zfbrh+Cgy36xQ7HBFSjOHqZrNOTpwO9VrrbpC0QQHXbl61KjFFJRA5n1Beil/InUDJ"

  - type: ssh
    description: "SSH 2222 (backup door)"
    host: "mandragot.org"
    port: 2222
    key: "mandragot.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqOpUUHHxr52MV10txU/F5Nd/5H1bcv7g49mripAbvH1N50wU5MecfwsA5sBm0maVrmHx8Z8LU5J1xGZtkXcsvTMF5h9CgotxR+M1VRShhpGpz/+CkplCbGNw030H+Mlr6rb6NLyO4TUtWM365JaCt5+JjSliBHt9lg0Sv88sl0RNff4EMeuDVmoGWQ5o+HZDuL0o7Cu/qJka9Xp0bqP/xBMrgIIXND/+A7Fd7Cb3oQGZBc4MPXv3DumqmfOlSG7Klue+7CUwS2ZYzUiVPmvZWq6rKeCRdRXtbqybBmbqTXP1+aj6sIuXt1NPtZ+imx/HVDqOl3mdNQl5yOysGm1XH"