version: '3'

services:
    monitor:
      build: ".."
      image: "drollcaller"
      restart: "unless-stopped"
      volumes:
        - "./example_monitoring_configuration.yml:/monitoring_configuration.yml:Z"